// !!! This is a file automatically generated by hipify!!!
#pragma once

#ifndef _TRITON_DRIVER_CONTEXT_H_
#define _TRITON_DRIVER_CONTEXT_H_

#include "triton/driver/device_hip.h"
#include "triton/driver/handle_hip.h"

namespace triton
{
namespace driver
{

class context: public polymorphic_resource<hipCtx_t, host_context_t>{
protected:
  static std::string get_cache_path();

public:
  context(driver::device *dev, hipCtx_t cu, bool take_ownership);
  context(driver::device *dev, host_context_t hst, bool take_ownership);
  driver::device* device() const;
  std::string const & cache_path() const;
  // factory methods
  static context* create(driver::device *dev);

protected:
  driver::device* dev_;
  std::string cache_path_;
};

// Host
class host_context: public context {
public:
  host_context(driver::device* dev);
};

// CUDA
class cu_context: public context {
private:
  static hipDevice_t get_device_of(hipCtx_t);
public:
  //Constructors
  cu_context(hipCtx_t cu, bool take_ownership = true);
  cu_context(driver::device* dev);
};

}
}

#endif
